version: '3'
services:
  # client:
  #   container_name: client
  #   build:
  #     context: client/.
  #   image: client
  #   restart: always
  #   ports:
  #   - 6001:6000
  #   depends_on:
  #   - rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
    - 5672:5672
    - 15672:15672
    restart: always
